version: "3.5"
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=my_vhost
  first-api:
    container_name: first-api
    image: mcr.microsoft.com/dotnet/sdk:5.0
    env_file:
      - .env
    environment: 
      - Zipkin__AppName=first-api
    volumes:
      - ./OpenTelemetryApi:/api
      - /obj/Debug/
    working_dir: /api
    depends_on:
      - rabbit
      - zipkin
    command: "dotnet run"
    ports:
      - "5000:5000"
  second-api:
    container_name: second-api
    image: mcr.microsoft.com/dotnet/sdk:5.0
    env_file:
      - .env
    environment: 
      - Zipkin__AppName=second-api
    volumes:
      - ./OpenTelemetryApi:/api
      - /obj/Debug/
    working_dir: /api
    depends_on:
      - rabbit
      - zipkin
    command: "dotnet run"
    ports:
      - "4000:5000"
  worker:
    container_name: worker
    image: mcr.microsoft.com/dotnet/sdk:5.0
    env_file:
      - .env
    environment: 
      - Zipkin__AppName=worker
    volumes:
      - .:/continuous
      - /obj/Debug/
    working_dir: /continuous/Worker
    depends_on:
      - rabbit
      - zipkin
    command:
      [
        "Scripts/wait-for-it.sh",
        "rabbit:5672",
        "-t",
        "30",
        "--",
        "dotnet",
        "run"
      ]
    ports:
      - "3000:5000"